package org.apache.jsp.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class DateSelector_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!--\r\n");
      out.write("\tDate Selector Pop-Up.\r\n");
      out.write("\tJavascript fully designed and developed by Fadi Chamieh - fadi.chamieh@google.com\r\n");
      out.write("\tVague Software. The Software @ vague-software.com\r\n");
      out.write("-->\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t<title>Easy Calendar - by Priya</title>\r\n");
      out.write("\t<style>\r\n");
      out.write("\t\tBODY {\r\n");
      out.write("\t\t\tfont-family: Verdana, Arial,Georgia;\r\n");
      out.write("\t\t\tcolor: Navy;\r\n");
      out.write("\t\t\tfont-size: 11px;\r\n");
      out.write("\t\t\tbackground-color: White;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tTD {\r\n");
      out.write("\t\t\tfont-family: Verdana, Arial,Georgia;\r\n");
      out.write("\t\t\tfont-size: 11px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tTEXTAREA {\r\n");
      out.write("\t\t\tfont-family: Verdana, Arial,Georgia;\r\n");
      out.write("\t\t\tbackground-color: #FFF4D9;\r\n");
      out.write("\t\t\tfont-size: 11px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tINPUT.fancy {\r\n");
      out.write("\t\t\tbackground-color: #FFFFFF;\r\n");
      out.write("\t\t\tborder-top: 1px #FBCB98 solid;\r\n");
      out.write("\t\t\tborder-right: 1px #FBCB98 solid;\r\n");
      out.write("\t\t\tborder-bottom: 2px #FBCB98 solid;\r\n");
      out.write("\t\t\tborder-left: 1px #FBCB98 solid;\r\n");
      out.write("\t\t\theight: 20px;\r\n");
      out.write("\t\t\tfont-family: Verdana, Arial,Georgia;\r\n");
      out.write("\t\t\tfont-size: 10px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tINPUT.fancyButton {\r\n");
      out.write("\t\t\tfont-family: Verdana, Arial,Georgia;\r\n");
      out.write("\t\t\tborder-right: #000000 1px solid;\r\n");
      out.write("\t\t\tborder-top: #000000 1px solid;\r\n");
      out.write("\t\t\tfont-weight: bold;\r\n");
      out.write("\t\t\tfont-size: 11px;\r\n");
      out.write("\t\t\tborder-left: #000000 1px solid;\r\n");
      out.write("\t\t\tcursor: hand;\r\n");
      out.write("\t\t\tcolor: Navy;\r\n");
      out.write("\t\t\tborder-bottom: #000000 1px solid;\r\n");
      out.write("\t\t\theight: 20px;\r\n");
      out.write("\t\t\tbackground-color: #ffb72b;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tSELECT {\r\n");
      out.write("\t\t\tfont-family: Verdana, Arial,Georgia;\r\n");
      out.write("\t\t\tfont-size: 11px;\r\n");
      out.write("\t\t\tbackground-color: #FFE4C9;\r\n");
      out.write("\t\t\tborder-top: 1px #000000 solid;\r\n");
      out.write("\t\t\tborder-right: 1px #000000 solid;\r\n");
      out.write("\t\t\tborder-bottom: 1px #000000 solid;\r\n");
      out.write("\t\t\tborder-left: 1px #000000 solid;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</style>\r\n");
      out.write("\t<script language=\"javascript\">\r\n");
      out.write("\r\n");
      out.write("\t\tvar DayInMilliseconds = 24 * 60 * 60 * 1000;\r\n");
      out.write("\t\tvar TodaysDate = new Date();\r\n");
      out.write("\t\tvar SelectedDate = TodaysDate;\r\n");
      out.write("\t\tvar OriginalDate = TodaysDate;\r\n");
      out.write("\t\tvar ColumnDayMapping = Array( 1, 2, 3, 4, 5, 6, 0 ); // 0-Monday ... 6-Sunday\r\n");
      out.write("\t\tvar previousYear = SelectedDate.getFullYear();\r\n");
      out.write("\t\t/*\r\n");
      out.write("\t\t * Show the calendar for the given month\r\n");
      out.write("\t\t */\r\n");
      out.write("\t\t function ShowCalendar(pYear, pMonth, pMonthDay)\r\n");
      out.write("\t\t {\r\n");
      out.write("\t\t \t// Valid entries only\r\n");
      out.write("\t\t \tpYear  = parseInt( pYear );  pYear = (isNaN( pYear ) || pYear < 1599 || pYear > 2999) ? TodaysDate.getFullYear() : pYear;\r\n");
      out.write("\t\t \tpMonth = parseInt( pMonth ); pMonth = isNaN( pMonth ) ? (TodaysDate.getMonth() + 1) : pMonth;\r\n");
      out.write("\t\t \tpMonthDay = parseInt( pMonthDay ); pMonthDay = isNaN( pMonthDay ) ? TodaysDate.getDate() : pMonthDay;\r\n");
      out.write("\r\n");
      out.write("\t\t\tpreviousYear = pYear;\r\n");
      out.write("\r\n");
      out.write("\t\t \tSelectedDate = new Date();\r\n");
      out.write("\t\t\tSelectedDate.setFullYear( pYear, pMonth - 1, pMonthDay );\r\n");
      out.write("\t\t\tdocument.frmDateSelection.theDate.value = formatDate( SelectedDate );\r\n");
      out.write("\r\n");
      out.write("\t\t \t// Get first and last days of the month\r\n");
      out.write("\t\t \tvar FirstDayOfMonth = new Date(), FirstDayOfNextMonth = new Date(), LastDayOfMonth = new Date();\r\n");
      out.write("\t\t \tFirstDayOfMonth.setFullYear( pYear, pMonth - 1, 1 );\r\n");
      out.write("\r\n");
      out.write("\t\t \tif(pMonth < 12) FirstDayOfNextMonth.setFullYear( pYear, pMonth, 1 );\r\n");
      out.write("\t\t \telse FirstDayOfNextMonth.setFullYear( pYear + 1, 0, 1 );\r\n");
      out.write("\r\n");
      out.write("\t\t \tLastDayOfMonth.setTime( FirstDayOfNextMonth.getTime() - DayInMilliseconds );\r\n");
      out.write("\r\n");
      out.write("\t\t \t// Loop over TD's and set their values accordingly\r\n");
      out.write("\t\t \tvar dayNo = 0;\r\n");
      out.write("\t\t \tfor( var r = 0; r < 6; r++ )\r\n");
      out.write("\t\t \t{\r\n");
      out.write("\t\t \t\tfor(var c = 0; c < 7; c++)\r\n");
      out.write("\t\t \t\t{\r\n");
      out.write("\t\t \t\t\tvar td = document.getElementById(\"GridTD_\" + r + \"_\" + c);\r\n");
      out.write("\t\t \t\t\t// Clean up the td\r\n");
      out.write("\t\t \t\t\ttd.innerHTML = \"&nbsp;\";\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t// Sundays and Saturdays are different\r\n");
      out.write("\t\t\t\t\t// if( c == 5 || c == 6 )\r\n");
      out.write("\t\t\t\t\t// \ttd.style.backgroundColor =\"#F0F0F0\";\r\n");
      out.write("\t\t\t\t\t// else\r\n");
      out.write(" \t\t\t\t\ttd.style.backgroundColor = \"\";\r\n");
      out.write(" \t\t\t\t\t\r\n");
      out.write(" \t\t\t\t\ttd.style.color = \"black\";\r\n");
      out.write(" \t\t\t\t\ttd.style.fontWeight = \"normal\";\r\n");
      out.write("\r\n");
      out.write("\t\t \t\t\t// If not started counting, check for start\r\n");
      out.write("\t\t \t\t\tif( dayNo == 0 )\r\n");
      out.write("\t\t \t\t\t\tif ( FirstDayOfMonth.getDay() == ColumnDayMapping[c] )\r\n");
      out.write("\t\t \t\t\t\t\tdayNo = 1;\r\n");
      out.write("\r\n");
      out.write("\t\t \t\t\tif( dayNo > 0 && dayNo <= LastDayOfMonth.getDate() )\r\n");
      out.write("\t\t \t\t\t{\r\n");
      out.write("\t\t \t\t\t\ttd.innerHTML = \"<a href='javascript:void(0);' onclick='javascript:ShowCalendar(\"+pYear+\",\"+pMonth+\",\"+dayNo+\")'>\"+ dayNo + \"</a>\";\r\n");
      out.write("\r\n");
      out.write("\t\t \t\t\t\tif( (TodaysDate.getFullYear() == pYear) && (TodaysDate.getMonth() == pMonth - 1) && (TodaysDate.getDate() == dayNo) )\r\n");
      out.write("\t\t \t\t\t\t{\r\n");
      out.write(" \t\t\t\t\t\t\ttd.style.fontWeight = \"bold\";\r\n");
      out.write("\t\t \t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t \t\t\t\tif( pMonthDay == dayNo )\r\n");
      out.write("\t\t \t\t\t\t{\r\n");
      out.write(" \t\t\t\t\t\t\ttd.style.backgroundColor = \"Yellow\";\r\n");
      out.write(" \t\t\t\t\t\t\ttd.style.color = \"red\";\r\n");
      out.write(" \t\t\t\t\t\t\ttd.style.fontWeight = \"bold\";\r\n");
      out.write("\t\t \t\t\t\t}\r\n");
      out.write("\t\t \t\t\t\t\t\t \t\t\t\t\r\n");
      out.write("\t\t \t\t\t\tdayNo++;\r\n");
      out.write("\t\t \t\t\t}\r\n");
      out.write("\t\t \t\t}\r\n");
      out.write("\t\t \t}\r\n");
      out.write("\t\t }\r\n");
      out.write("\r\n");
      out.write("\t\t/*\r\n");
      out.write("\t\t * Returned Date format\r\n");
      out.write("\t\t */\r\n");
      out.write("\t\t function formatDate( dateObject )\r\n");
      out.write("\t\t {\r\n");
      out.write("\t\t \tvar pMonth = dateObject.getMonth() + 1;\r\n");
      out.write("\t\t \tvar pMonthDay = dateObject.getDate();\r\n");
      out.write("\t\t \tvar pYear = dateObject.getFullYear();\r\n");
      out.write("\r\n");
      out.write("\t\t \t// Show day, month and year readings\r\n");
      out.write("\t\t \tvar disp_Month = (pMonth < 10) ? \"0\" + pMonth : pMonth;\r\n");
      out.write("\t\t \tvar disp_Day = (pMonthDay  < 10) ? \"0\" + pMonthDay  : pMonthDay;\r\n");
      out.write("\t\t \tdocument.frmDateSelection.month.selectedIndex = pMonth - 1;\r\n");
      out.write("\t\t \tdocument.frmDateSelection.year.value = pYear;\r\n");
      out.write("\t\t \treturn disp_Day + \"-\" + disp_Month + \"-\" + pYear;\r\n");
      out.write("\t\t }\r\n");
      out.write("\r\n");
      out.write("\t\t/*\r\n");
      out.write("\t\t * Month changed\r\n");
      out.write("\t\t */\r\n");
      out.write("\t\t function MonthOrYearChanged()\r\n");
      out.write("\t\t {\r\n");
      out.write("\t\t\tShowCalendar( document.frmDateSelection.year.value, document.frmDateSelection.month.selectedIndex + 1, 1 );\r\n");
      out.write("\t\t }\r\n");
      out.write("\r\n");
      out.write("\t\t// +1/-1 Year change\r\n");
      out.write("\t\tfunction YearChanged( howMuch )\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tdocument.frmDateSelection.year.value = parseInt( document.frmDateSelection.year.value ) + parseInt( howMuch );\r\n");
      out.write("\t\t\tMonthOrYearChanged();\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t// Parse a date string and return the object\r\n");
      out.write("\t\tfunction getDateObject( dateString )\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tvar arr = Array();\r\n");
      out.write("\t\t\tvar valid = false;\r\n");
      out.write("\t\t\tvar day = -1, month = -1, year = -1;\r\n");
      out.write("\r\n");
      out.write("\t\t\t// dd/mm/yyyy format\r\n");
      out.write("\t\t\tif( dateString.indexOf(\"/\") > 0 )\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tvalid = true;\r\n");
      out.write("\t\t\t\tarr   = dateString.split(\"/\");\r\n");
      out.write("\t\t\t\tday = parseInt(arr[0],10);\r\n");
      out.write("\t\t\t\tif(arr.length > 0) month = parseInt(arr[1],10);\r\n");
      out.write("\t\t\t\tif(arr.length > 1) year  = parseInt(arr[2],10);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t// yyyy-mm-dd\r\n");
      out.write("\t\t\telse if( dateString.indexOf(\"-\") > 0 )\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tvalid = true;\r\n");
      out.write("\t\t\t\tarr   = dateString.split(\"-\");\r\n");
      out.write("\t\t\t\tday = parseInt(arr[2],10);\r\n");
      out.write("\t\t\t\tif(arr.length > 0) month = parseInt(arr[1],10);\r\n");
      out.write("\t\t\t\tif(arr.length > 1) year  = parseInt(arr[0],10);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\tif(! valid ) return TodaysDate;\r\n");
      out.write("\r\n");
      out.write("\t\t\tday = parseInt(arr[0],10);\r\n");
      out.write("\t\t\tif(arr.length > 0) month = parseInt(arr[1],10);\r\n");
      out.write("\t\t\tif(arr.length > 1) year  = parseInt(arr[2],10);\r\n");
      out.write("\r\n");
      out.write("\t\t\tvar theDate = new Date();\r\n");
      out.write("\r\n");
      out.write("\t\t\ttheDate.setFullYear( year, month - 1, day );\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\treturn theDate;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t/*\r\n");
      out.write("\t\t * Initialize\r\n");
      out.write("\t\t */\r\n");
      out.write("\t\tfunction Initialize( fromDateObj )\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tpreviousYear = SelectedDate.getFullYear();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif( ! fromDateObj )\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tvar validSelected = false;\r\n");
      out.write("\t\t\t\ttry\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\tif(window.opener != null)\r\n");
      out.write("\t\t\t\t\t\tSelectedDate = opener.GetDateSelectorDate();\r\n");
      out.write("\t\t\t\t\tif( typeof(SelectedDate) == \"object\" )\r\n");
      out.write("\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\tvalidSelected = true;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\telse\r\n");
      out.write("\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\tSelectedDate = getDateObject( SelectedDate );\r\n");
      out.write("\t\t\t\t\t\tvalidSelected = true;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tcatch( ex )\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\tvalidSelected = false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tif( ! validSelected ) SelectedDate = TodaysDate;\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tOriginalDate = SelectedDate;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tSelectedDate = fromDateObj;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tdocument.frmDateSelection.year.focus();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tShowCalendar( SelectedDate.getFullYear(), SelectedDate.getMonth() + 1, SelectedDate.getDate() );\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tfunction returnDateString()\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\ttry\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tif(window.opener != null)\r\n");
      out.write("\t\t\t\t\topener.SetDateSelectorDate( document.frmDateSelection.theDate.value );\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tcatch( ex )\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\talert(\"Wrong use of returnDateString() function\\n\" + ex.toString());\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\twindow.close();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body topmargin=\"0\" rightmargin=\"0\" leftmargin=\"0\" bottommargin=\"0\" style=\"margin: 0px;\" onload=\"Initialize()\">\r\n");
      out.write("\r\n");
      out.write("\t\t<table border=\"1\" cellpadding=\"5\" cellspacing=\"2\" bordercolor=\"#FFFFFF\" align=\"center\" height=\"100%\">\r\n");
      out.write("        <form name=\"frmDateSelection\" method=\"post\" action=\"\">\r\n");
      out.write("\t\t    <tr>\r\n");
      out.write("              <td bordercolor=\"#FFCC00\"><table border=\"0\" cellspacing=\"2\" cellpadding=\"2\">\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td><table border=\"0\" cellpadding=\"2\" cellspacing=\"0\">\r\n");
      out.write("                        <tr>\r\n");
      out.write("                          <td align=\"right\">\r\n");
      out.write("                          \t<table border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("                              <tr>\r\n");
      out.write("                                <td><table border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("                                    <tr>\r\n");
      out.write("                                      <td><a href=\"javascript:YearChanged(1);\"><img src=\"");
      out.print(request.getContextPath());
      out.write("/Images/up.gif\" width=\"12\" height=\"8\" border=\"0\"></a></td>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                    <TR><td></td></tr>\r\n");
      out.write("                                    <TR><td></td></tr>\r\n");
      out.write("                                    <tr>\r\n");
      out.write("                                      <td><a href=\"javascript:YearChanged(-1);\"><img src=\"");
      out.print(request.getContextPath());
      out.write("/Images/down.gif\" width=\"12\" height=\"8\" border=\"0\"></a></td>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                </table></td>\r\n");
      out.write("                                <td align=\"right\"><input name=\"year\" type=\"text\" class=\"fancy\" style=\"width:40px\" maxlength=\"4\" value=\"2004\" onchange=\"MonthOrYearChanged()\" onkeyup=\"if(this.value.length == 4 && previousYear != this.value) MonthOrYearChanged()\"></td>\r\n");
      out.write("                              </tr>\r\n");
      out.write("                          </table></td>\r\n");
      out.write("                          <td><select name=\"month\" class=\"fancy\" id=\"month\" onchange=\"MonthOrYearChanged()\" style=\"width:160px\">\r\n");
      out.write("                          \t  <option value=\"01\">January</option>\r\n");
      out.write("                              <option value=\"02\">February</option>\r\n");
      out.write("                              <option value=\"03\">March</option>\r\n");
      out.write("                              <option value=\"04\">April</option>\r\n");
      out.write("\t\t\t\t\t\t\t  <option value=\"05\">May</option>\r\n");
      out.write("                          \t  <option value=\"06\">June</option>\r\n");
      out.write("                              <option value=\"07\">July</option>\r\n");
      out.write("                              <option value=\"08\">August</option>\r\n");
      out.write("                              <option value=\"09\">September</option>\r\n");
      out.write("\t\t\t\t\t\t\t  <option value=\"10\">October</option>\r\n");
      out.write("                          \t  <option value=\"11\">November</option>\r\n");
      out.write("                              <option value=\"02\">December</option>\r\n");
      out.write("\t\t\t\t\t\t\t</select></td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    </table></td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td>\r\n");
      out.write("\t\t\t\t\t\t<table border=\"1\" cellspacing=\"1\" bordercolor=\"Silver\" cellpadding=\"3\">\r\n");
      out.write("                        <tr align=\"center\" bgcolor=\"#FFCC00\">\r\n");
      out.write("                          <td width=\"25\">Mon</td>\r\n");
      out.write("                          <td width=\"25\">Tue</td>\r\n");
      out.write("                          <td width=\"25\">Wed</td>\r\n");
      out.write("                          <td width=\"25\">Thu</td>\r\n");
      out.write("                          <td width=\"25\">Fri</td>\r\n");
      out.write("                          <td width=\"25\">Sat</td>\r\n");
      out.write("                          <td width=\"25\">Sun</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <script language=\"javascript\">\r\n");
      out.write("\t\t\t\t\t\t\tvar InlineHTML = \"\";\r\n");
      out.write("\t\t\t\t\t\t\tfor(var i = 0; i < 6; i++)\r\n");
      out.write("\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\tInlineHTML += \"<tr align=center>\";\r\n");
      out.write("\t\t\t\t\t\t\t\tfor(var j = 0; j < 7; j++)\r\n");
      out.write("\t\t\t\t\t\t\t\t\tInlineHTML += \"<td id='GridTD_\"+ i +\"_\"+ j +\"'>&nbsp;</td>\";\r\n");
      out.write("\t\t\t\t\t\t\t\tInlineHTML += \"</tr>\"\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\tdocument.writeln( InlineHTML );\r\n");
      out.write("                        </script>\r\n");
      out.write("                    </table></td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\"   style=\"width:70px;color:red;\" name=\"theDate\" readonly=\"true\" value=\"\" class=\"fancy\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" style=\"width:25px;color=Black\"  name=\"btnOk\" value=\"OK\" onclick=\"returnDateString()\" class=\"fancyButton\">\r\n");
      out.write("                        <input type=\"button\" style=\"width:50px;color=Black\"  name=\"btnCancel\" value=\"Cancel\" onclick=\"window.close()\" class=\"fancyButton\">\r\n");
      out.write("                        <input type=\"button\" style=\"width:48px;color=Blue\"  name=\"btnToday\" value=\"Today\" onclick=\"Initialize( TodaysDate )\" class=\"fancyButton\">\r\n");
      out.write("                        <input type=\"button\" style=\"width:42px;color=Green\"  name=\"btnRest\" value=\"Reset\" onclick=\"Initialize( OriginalDate )\" class=\"fancyButton\" ID=\"Button1\">\r\n");
      out.write("                    </td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("              </table></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("       </table>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
